apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "clusterclass-quickstart"
  namespace: default
  labels:
    cni: kindnet
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.128.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: clusterclass
    version: v1.21.2
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: linux-worker
          name: linux-workers
          replicas: 1
